'use client';

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
// import { useTheme } from 'next-themes';

const TermsAndConditions: React.FC = () => {
  // const { theme } = useTheme();
  
  return (
    <main className="flex-grow flex items-center justify-center p-6 bg-white text-black dark:bg-black dark:text-white">
      <Card className="w-full max-w-4xl shadow-2xl bg-white text-black dark:bg-black dark:text-white">
        <CardHeader className="border-b border-gray-300 dark:border-gray-600">
          <CardTitle className="text-3xl font-bold">Terms and Conditions</CardTitle>
        </CardHeader>
        <CardContent className="p-8">
          <div className="space-y-8 text-lg">
            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-600 dark:text-gray-300">1. Introduction</h2>
              <p>
                Welcome to Vakeel.ai. By accessing or using our service, you agree to these Terms and Conditions.
                Please read them carefully before using our platform.
              </p>
            </section>

            <Separator className="my-6 border-gray-300 dark:border-gray-600" />

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-600 dark:text-gray-300">2. Service Usage</h2>
              <p>2.1 Vakeel.ai provides AI-powered legal assistance and document generation services.</p>
              <p>2.2 You agree to use the service for lawful purposes only and not to:</p>
              <ul className="list-disc list-inside ml-6 mt-2 space-y-1">
                <li>Violate any applicable laws</li>
                <li>Infringe on intellectual property rights</li>
                <li>Engage in fraudulent activities</li>
              </ul>
            </section>

            <Separator className="my-6 border-gray-300 dark:border-gray-600" />

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-600 dark:text-gray-300">3. Intellectual Property</h2>
              <p>3.1 All content generated by Vakeel.ai remains the property of the user, subject to our usage terms.</p>
              <p>3.2 Vakeel.ai retains the right to use anonymized data for service improvement.</p>
            </section>

            <Separator className="my-6 border-gray-300 dark:border-gray-600" />

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-600 dark:text-gray-300">4. Limitation of Liability</h2>
              <p>4.1 Vakeel.ai provides services as is and does not guarantee absolute accuracy of legal documents.</p>
              <p>4.2 Users are advised to consult with a qualified legal professional for critical legal matters.</p>
            </section>

            <Separator className="my-6 border-gray-300 dark:border-gray-600" />

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-600 dark:text-gray-300">5. Privacy</h2>
              <p>5.1 Your use of Vakeel.ai is also governed by our Privacy Policy.</p>
              <p>5.2 We are committed to protecting your personal and legal information.</p>
            </section>

            <Separator className="my-6 border-gray-300 dark:border-gray-600" />

            <section>
              <h2 className="text-2xl font-semibold mb-4 text-gray-600 dark:text-gray-300">6. Termination</h2>
              <p>6.1 Vakeel.ai reserves the right to terminate or suspend accounts that violate these terms.</p>
              <p>6.2 Users may terminate their account at any time by contacting our support team.</p>
            </section>
          </div>
        </CardContent>
      </Card>
    </main>
  );
};

export default TermsAndConditions;
